service-name: team35_auth

port: 3001
grpc-port: 4000
port-metrics: 9001

mongo-conn: mongodb://team35:mNgd1MTbhVGd@91.185.93.34:27017/team35
mongo-db: team35

profiler: false

dsn: https://1c93b31416214f6faabbe99c0cf0b351@sentry.k8s.golang-mts-teta.ru/24

jaeger-collector: http://jaeger-instance-collector.observability:14268/api/traces

swagger-host: localhost:3000
swagger-base-path: